//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.11.2
//     from Assets/InArenaControls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @InArenaControls: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @InArenaControls()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""InArenaControls"",
    ""maps"": [
        {
            ""name"": ""Player"",
            ""id"": ""fa740a02-11e0-41b8-9b32-e2c5db3a9c8b"",
            ""actions"": [
                {
                    ""name"": ""LShift"",
                    ""type"": ""PassThrough"",
                    ""id"": ""273aa178-46ea-44e7-a223-fe4e8fff3b4c"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""LControl"",
                    ""type"": ""PassThrough"",
                    ""id"": ""8fe55271-de13-4199-8467-3750bee87196"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""LAlt"",
                    ""type"": ""PassThrough"",
                    ""id"": ""a7a0cfb7-4884-4496-9a2b-9708da1ec7b5"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""LClick"",
                    ""type"": ""PassThrough"",
                    ""id"": ""3de614cb-42ae-4aa2-9d71-7d9dab077a79"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""47575d02-fa29-4f79-b901-67c42cb0e1ab"",
                    ""path"": ""<Keyboard>/leftShift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LShift"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""256398d9-a93b-4dd5-9f87-cad7aa33b216"",
                    ""path"": ""<Keyboard>/ctrl"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LControl"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3af16b46-d4da-4afb-86fe-6c8e9fa6aad1"",
                    ""path"": ""<Keyboard>/alt"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LAlt"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6628b42a-e904-4783-97d8-f2d7cb2a209c"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LClick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Player
        m_Player = asset.FindActionMap("Player", throwIfNotFound: true);
        m_Player_LShift = m_Player.FindAction("LShift", throwIfNotFound: true);
        m_Player_LControl = m_Player.FindAction("LControl", throwIfNotFound: true);
        m_Player_LAlt = m_Player.FindAction("LAlt", throwIfNotFound: true);
        m_Player_LClick = m_Player.FindAction("LClick", throwIfNotFound: true);
    }

    ~@InArenaControls()
    {
        UnityEngine.Debug.Assert(!m_Player.enabled, "This will cause a leak and performance issues, InArenaControls.Player.Disable() has not been called.");
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Player
    private readonly InputActionMap m_Player;
    private List<IPlayerActions> m_PlayerActionsCallbackInterfaces = new List<IPlayerActions>();
    private readonly InputAction m_Player_LShift;
    private readonly InputAction m_Player_LControl;
    private readonly InputAction m_Player_LAlt;
    private readonly InputAction m_Player_LClick;
    public struct PlayerActions
    {
        private @InArenaControls m_Wrapper;
        public PlayerActions(@InArenaControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @LShift => m_Wrapper.m_Player_LShift;
        public InputAction @LControl => m_Wrapper.m_Player_LControl;
        public InputAction @LAlt => m_Wrapper.m_Player_LAlt;
        public InputAction @LClick => m_Wrapper.m_Player_LClick;
        public InputActionMap Get() { return m_Wrapper.m_Player; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PlayerActions set) { return set.Get(); }
        public void AddCallbacks(IPlayerActions instance)
        {
            if (instance == null || m_Wrapper.m_PlayerActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_PlayerActionsCallbackInterfaces.Add(instance);
            @LShift.started += instance.OnLShift;
            @LShift.performed += instance.OnLShift;
            @LShift.canceled += instance.OnLShift;
            @LControl.started += instance.OnLControl;
            @LControl.performed += instance.OnLControl;
            @LControl.canceled += instance.OnLControl;
            @LAlt.started += instance.OnLAlt;
            @LAlt.performed += instance.OnLAlt;
            @LAlt.canceled += instance.OnLAlt;
            @LClick.started += instance.OnLClick;
            @LClick.performed += instance.OnLClick;
            @LClick.canceled += instance.OnLClick;
        }

        private void UnregisterCallbacks(IPlayerActions instance)
        {
            @LShift.started -= instance.OnLShift;
            @LShift.performed -= instance.OnLShift;
            @LShift.canceled -= instance.OnLShift;
            @LControl.started -= instance.OnLControl;
            @LControl.performed -= instance.OnLControl;
            @LControl.canceled -= instance.OnLControl;
            @LAlt.started -= instance.OnLAlt;
            @LAlt.performed -= instance.OnLAlt;
            @LAlt.canceled -= instance.OnLAlt;
            @LClick.started -= instance.OnLClick;
            @LClick.performed -= instance.OnLClick;
            @LClick.canceled -= instance.OnLClick;
        }

        public void RemoveCallbacks(IPlayerActions instance)
        {
            if (m_Wrapper.m_PlayerActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IPlayerActions instance)
        {
            foreach (var item in m_Wrapper.m_PlayerActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_PlayerActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public PlayerActions @Player => new PlayerActions(this);
    public interface IPlayerActions
    {
        void OnLShift(InputAction.CallbackContext context);
        void OnLControl(InputAction.CallbackContext context);
        void OnLAlt(InputAction.CallbackContext context);
        void OnLClick(InputAction.CallbackContext context);
    }
}
